//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DLoader.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_BMOPR_NOTREG                103
#define IDD_EDT_BTN_DLG                 104
#define IDS_ATL_INIT_FAIL               105
#define IDD_PROPPAGE_MAIN               106
#define IDD_PROPPAGE_LCD                107
#define IDS_NEWOPR_FAIL                 108
#define IDS_CREATETHREAD_FAIL           109
#define IDS_FILEINFO_ERROR              110
#define IDS_START_FAIL                  111
#define IDR_MAINFRAME                   128
#define IDR_DLOADETYPE                  129
#define IDD_DIALOG_MODE_SETTINGS        137
#define IDD_DIALOG_CALIBRATION_SETTINGS 138
#define IDD_DIALOG_NAND_SETTINGS        139
#define IDB_BMP_TOOLBAR                 143
#define IDB_BMP_TOOLBAR_HOT             145
#define IDB_BMP_TOOLBAR_DIS             146
#define IDB_TB_BACKGRND                 147
#define IDB_BMP_PROG_BLOCK              152
#define IDB_BMP_FOLDER                  153
#define IDB_BMP_TM                      158
#define IDD_DLG_PAKET_SETTING           161
#define IDD_DIALOG_BARCODE              163
#define IDB_BITMAP_START                168
#define IDI_ICON_OK                     169
#define IDI_ICON_PAUSE                  170
#define IDD_DIALOG_MULTI_LANG           171
#define IDD_PROPPAGE_FLASH              172
#define IDB_BMP_PROG_BROWN              173
#define IDB_BMP_LANG_ICON               174
#define IDB_BMP_TB_FACTORY              178
#define IDB_BMP_TB_FACTORY_HOT          179
#define IDB_BMP_TB_FACTORY_DIS          180
#define IDB_BMP_TB_UPGRADE              181
#define IDB_BMP_TB_UPGRADE_HOT          182
#define IDB_BMP_TB_UPGRADE_DIS          183
#define IDD_DLG_PASSWORD                185
#define IDD_PROPPAGE_MCP                186
#define IDD_PROPPAGE_OPTIONS            187
#define IDD_PROPPAGE_VOL_FREQ           188
#define IDD_COMBOX_DLG                  189
#define IDD_PROPPAGE_UART_PORT_SWITCH   190
#define IDD_PROPPAGE_CUSTOMIZATION      191
#define IDD_PROPPAGE_CUST               192
#define IDC_BTN_START1                  301
#define IDC_BTN_START2                  302
#define IDC_BTN_START3                  303
#define IDC_BTN_START4                  304
#define IDC_BTN_START5                  305
#define IDC_BTN_START6                  306
#define IDC_BTN_START7                  307
#define IDC_BTN_START8                  308
#define IDC_BTN_START9                  309
#define IDC_BTN_START10                 310
#define IDC_BTN_START11                 311
#define IDC_BTN_START12                 312
#define IDC_BTN_START13                 313
#define IDC_BTN_START14                 314
#define IDC_BTN_START15                 315
#define IDC_BTN_START16                 316
#define IDC_BTN_START17                 317
#define IDC_BTN_START18                 318
#define IDC_BTN_START19                 319
#define IDC_BTN_START20                 320
#define IDC_BTN_START21                 321
#define IDC_BTN_START22                 322
#define IDC_BTN_START23                 323
#define IDC_BTN_START24                 324
#define IDC_STATIC_BUILD                1045
#define IDC_STATIC_VERSION              1046
#define IDC_COMBO_FLASH_TYPE            1050
#define IDC_CHECK_MANUAL_TO_BOOT        1051
#define IDC_WAIT_TIME_EDIT              1059
#define IDC_WAIT_TIME_BOOT_EDIT         1060
#define IDC_RADIO_REPARTITION_ALWAYS    1062
#define IDC_RADIO_REPARTITION_STOP      1063
#define IDC_RADIO_REPARTITION_IGNORE    1064
#define IDC_RADIO_REPARTITION_DO        1065
#define IDC_CMB_PORT                    1066
#define IDC_CMB_BAUDRATE                1067
#define IDC_CHK_ALL                     1068
#define IDC_CMB_PRODUCT                 1069
#define IDC_LST_PRODUCT_INFO            1070
#define IDC_EDT_TEXT                    1073
#define IDC_BTN_SEL                     1074
#define IDC_LIST_FRAME                  1077
#define IDC_STATIC_PRODUCT_NAME         1078
#define IDC_STC_PROD_COMMENT            1080
#define IDC_STC_PRD_VER                 1083
#define IDC_STC_SAVE_PATH               1085
#define IDC_BTN_BROWSE                  1086
#define IDC_EDT_PRD_VERSION             1087
#define IDC_EDT_PRD_VER                 1088
#define IDC_STC_SEL_PRD                 1089
#define IDC_EDT_PRD_ALIAS               1089
#define IDC_EDT_PATH                    1090
#define IDC_PS_STC_PRD_NANE             1091
#define IDC_CHK_SAVE_TO_LOCAL           1092
#define IDC_STC_LOCAL_PATH              1093
#define IDC_DC_EDT_PATH                 1094
#define IDC_DC_BTN_BROWSE               1095
#define IDC_STC_VER_SAP                 1096
#define IDC_EDIT_BARCODE                1097
#define IDC_BUTTON_SUSPEND              1099
#define IDC_DML_LST_LANG                1100
#define IDC_DML_CHK_BACKUP_LANG         1101
#define IDC_DML_STC_TIPS                1102
#define IDC_NFD_STC_FLASH_TYPE          1103
#define IDC_NFD_STC_GRP                 1104
#define IDC_DML_STC_NOTICE              1105
#define IDC_FOD_LST_READ                1112
#define IDC_FOD_CHK_ACTIVE_READ_FLASH   1113
#define IDC_FOD_BTN_DEL                 1114
#define IDC_MPD_CHK_SN                  1116
#define IDC_LCP_LST_LCD_CONFIG          1117
#define IDC_LCD_STC_TIPS                1118
#define IDC_FOD_LST_ERASE               1118
#define IDC_FOD_CHK_ACTIVE_ERASE_FLASH  1119
#define IDC_EDT_PASSWORD                1120
#define IDC_FOD_BTN_DELE                1120
#define IDC_BTN_RESET                   1121
#define IDC_FOD_LST_WRITE               1121
#define IDC_EDT_NEW_PASSWORD            1122
#define IDC_FOD_CHK_ACTIVE_WRITE_FLASH  1122
#define IDC_EDT_NEW_PASSWORD2           1123
#define IDC_FOD_BTN_DELW                1123
#define IDC_STC_GP_NEW                  1124
#define IDC_STC_NEW_PW                  1125
#define IDC_STC_NEW_PW2                 1126
#define IDC_FOD_CHK_ERASE_ALL           1127
#define IDC_MCP_CHK_MCPTYPE             1128
#define IDC_MCP_LST_MCP                 1130
#define IDC_MCP_BTN_ADD_MCP             1131
#define IDC_FOD_CHK_READ_MCPTYPE        1132
#define IDC_DOP_REPART                  1133
#define IDC_DOP_RESET                   1134
#define IDC_LST_FILE_BACKUP             1135
#define IDC_DOP_CHK_KEEP_CHARGE         1136
#define IDC_CHK_DDR_CHECK               1137
#define IDC_VFT_EDT_CLK_CA7_CORE        1138
#define IDC_CHK_SELF_REFRESH            1138
#define IDC_VFT_EDT_DDR_FREQ            1139
#define IDC_CHK_SELF_REFRESH2           1139
#define IDC_CHK_OLD_MEMORY              1139
#define IDC_VFT_CMB_CLK_CA7_AHB         1140
#define IDC_VFT_EDT_CLK_CA7_AXI         1141
#define IDC_VFT_EDT_CLK_CA7_GDB         1142
#define IDC_VFT_EDT_DCDC_ARM            1143
#define IDC_VFT_EDT_DCDC_MEM            1144
#define IDC_VFT_CMB_DEBUG               1145
#define IDC_VFT_CMB_CLK_CA7_APB         1146
#define IDC_VFT_CMB_CLK_PUB_AHB         1147
#define IDC_VFT_CMB_CLK_AON_APB         1148
#define IDC_VFT_EDT_DCDC_CORE           1150
#define IDC_VFT_EDT_DCDC_GEN            1151
#define IDC_VFT_EDT_DEBUG               1152
#define IDC_DOP_POWER_OFF               1153
#define IDC_CHECK_READ_CHIPUID          1154
#define IDC_LIST_SPL_TURNING            1155
#define IDC_STATIC_VOL_RANGE            1156
#define IDC_STATIC_CLK_CA7_CORE         1157
#define IDC_STATIC_DDR_FREQ             1158
#define IDC_STATIC_CLK_CA7_AXI          1159
#define IDC_STATIC_CLK_CA7_GDB          1160
#define IDC_STATIC_CLK_CA7_AHB          1161
#define IDC_STATIC_CLK_CA7_APB          1162
#define IDC_STATIC_CLK_PUB_AHB          1163
#define IDC_STATIC_CLK_AON_APB          1164
#define IDC_STATIC_DCDC_ARM             1165
#define IDC_STATIC_DCDC_CORE            1166
#define IDC_STATIC_DCDC_MEM             1167
#define IDC_STATIC_DCDC_GEN             1168
#define IDC_STATIC_DEBUG                1169
#define IDC_COMBO_LIST                  1170
#define IDC_CHK_CHECK_MATCH             1171
#define IDC_CHK_ENABLE_SECUREBOOT       1172
#define IDC_CHK_ENABLE_DL_LOG           1173
#define IDC_CHK_DEBUG_MODE              1174
#define IDC_CHECK_READFLASH_ALL         1175
#define IDC_CHK_EMMC_CHECK              1176
#define IDC_LIST_UART_PORT_TURNING      1177
#define IDC_STATIC_RANGE                1178
#define IDC_CHECK_CU                    1181
#define IDC_EDIT_CU                     1182
#define IDC_CHECK_ROOT                  1183
#define IDC_CHECK_BAD_FLASH_RATE        1184
#define IDC_EDIT_BAD_FLASH_RATE         1185
#define IDC_GROUP_CU                    1186
#define IDC_GROUP_ROOT                  1187
#define IDC_CHECK_UART_MODE             1188
#define IDC_CHECK_INPRODUCTION          1189
#define IDC_CHECK_AUTO_COMPARE          1190
#define IDC_EDIT_COMPARE_APP            1191
#define IDC_BUTTON_SELECT_COMPARE_APP   1192
#define IDC_STATIC_COMPARISON_TEXT      1193
#define IDC_GROUP_OTHERS                1194
#define ID_SETTINGS                     32771
#define ID_START                        32772
#define ID_STOP                         32773
#define ID_LOAD_PACKET                  32776
#define ID_SPD_VERSION                  32777
#define IDS_QUIT_TEST                   61204
#define IDS_DL_SETTINGS                 61211
#define IDS_LOAD_SETTINGS_FAIL          61214
#define IDS_PRODUCT_INFO_COLUMN         61216
#define IDS_ERR_FDL_NOT_CHECKED         61217
#define IDS_ERR_FILE_EMPTY              61218
#define IDS_NV_BKP_OPTION_COLUMN        61219
#define IDS_NV_BKP_FLAG_REPLACE         61220
#define IDS_NV_BKP_FLAG_CONTINUE        61221
#define IDS_BAUDRATE_DEFAULT            61222
#define IDS_ERR_LOAD_PACKET_FAIL        61223
#define IDS_ERR_FILES_NOT_EXIST         61225
#define IDS_MULTI_LANG_TIPS             61227
#define IDS_READ_FLASH_LIST_COL         61228
#define IDS_ERR_ITEM_EMPTY              61229
#define IDS_LCD_TIPS                    61230
#define IDS_MCP_LIST_COL                61231
#define IDS_VIEW_LIST_HDR               61232
#define IDS_STAGE_NONE                  61233
#define IDS_STAGE_CHECK_BAUD            61234
#define IDS_STAGE_CONNECT               61235
#define IDS_STAGE_ERASE_FLASH           61236
#define IDS_STAGE_DOWNLOAD              61237
#define IDS_STAGE_READ                  61238
#define IDS_STAGE_RESET                 61239
#define IDS_STAGE_READ_CHIPTYPE         61240
#define IDS_STAGE_READ_NVITEM           61241
#define IDS_STAGE_CHANGE_BAUD           61242
#define IDS_STAGE_FINISH                61243
#define IDS_STAGE_UNPLUGGED             61244
#define IDS_STAGE_PAUSED                61245
#define IDS_FILE_BACK_COLUMN            61246

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1195
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
